Updated kernel-mz.properties
kernel-notifier failing in uat2 because of 
Mail health check failed
javax.mail.AuthenticationFailedException: 535 Authentication failed: The provided authorization grant is invalid